### ISSUE TITLE
Error during NuPIC installation on air-gap computer

### ISSUE THREAD

**Issue by abuMAK** [htm-community/nupic.cpp#351] opened 2019-03-28 09:39 UTC
Hello ,
During the installation process I received an error message.
![NUPIC_ERROR](https://user-images.githubusercontent.com/33699727/55146878-0aae3a00-514e-11e9-8079-fe0589e839b4.png)
I attached the log files from the installation process
[CMakeError_ThirdParty.log](https://github.com/htm-community/nupic.cpp/files/3017177/CMakeError_ThirdParty.log)
[CMakeOutput_script.log](https://github.com/htm-community/nupic.cpp/files/3017178/CMakeOutput_script.log)
[CMakeOutput_ThirdParty.log](https://github.com/htm-community/nupic.cpp/files/3017179/CMakeOutput_ThirdParty.log)
Thanks,
MAK

**Comment by dkeeney** [comment] 2019-03-28 13:54
@abuMAK   I was expecting the logs to show me what happened but it does not.
There is the error when it tries to see if pthreads exist but that is normal.

So, I want you to try something else.
- close MSVC if you have it running.
- move the folder `build/ThirdParty/share` someplace out of the way, (I do not want you to loose your downloads)
- delete the entire `build` folder and everything under it.
- create `build/ThirdParty` folder and move your `share` folder back to `build/ThirdParty/share`.
- double click on startupMSVC.bat

This script should run and stop with a prompt to press enter to start MSVC or on some sort of error.  Highlight the entire contents of the command prompt screen and then copy it by pressing the Return key on your keyboard.  Paste this text into this issue screen.

If there is a lot of text you may have to scroll to highlight everything.  You might have to increase the  Layout Screen buffer size in your command prompt too in order to capture it all.  To do that, right click on top border and select properties, then Layout tab. Mine is set at a Height of 9000. You will probably also need 'QuickEdit Mode' in the Options tab in order to select text.

Once you get that text, please paste it here in this issue.  Hopefully I will be able to see what is going on.

Thanks.

**Comment by abuMAK** [comment] 2019-04-01 14:00
Hii @dkeeney ,
Thanks for your answer,
I attached the log that display into the CMD screen during the installation process.
Thanks,
MAK
[error.txt](https://github.com/htm-community/nupic.cpp/files/3029754/error.txt)

**Comment by dkeeney** [comment] 2019-04-01 18:45
@abuMAK Thank you for the log.  
I can now see what is happening... Yaml is confused or corrupted.
I will see if I can reproduce this error so I can give you an answer as to how to fix it.

**Comment by dkeeney** [comment] 2019-04-01 23:53
@abuMAK  I was able to reproduce your errors.
What I did was download the latest release of yaml-cpp (0.6.2) which was found at https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.6.2.zip.   I don't know what is actually in that release but the code in the release does not match the release notes.  This release does not build and gives the errors that you were seeing.
```
 error C3646: '_NOEXCEPT': unknown override specifier 
```

Somehow I think you got version 0.6.2.   So, if you download the zip of the master repository I think you will find that it will build correctly.
```
https://github.com/jbeder/yaml-cpp/archive/master.zip
```

However.  Now that you have the yaml-cpp 0.6.2 in there, you will need to remove it before you can use the new download.  The easiest way is to repeat the procedure I gave you before.   That makes sure that you delete everything in the build/ folder (except your downloads in build/ThirdParty/share).  Then download the yaml-cpp master.zip from another machine, renaming it yaml-cpp.zip and copy it to your share folder on the air-gap computer.

Give that a try and see if it works.

**Comment by breznak** [comment] 2019-04-02 10:52
>  I don't know what is actually in that release but the code in the release does not match the release notes. This release does not build and gives the errors that you were seeing. 

many thanks @dkeeney for this detective work! 
I recall you having a comment about some weird release there not matching the patches mentioned. 

- is this mentioned in our Readme? Ie is this a user install fault, or our doc is incomplete? 
- is it worth implementing hash checksums to avoid this kind of hidden mistakes? (that brings other negatives, esp with downloading "master", which will change in time)

**Comment by dkeeney** [comment] 2019-04-02 13:41
I agree this is a problem.  Checksums would not help because no checksum is provided for this release.  Our documentation says to use the master but it does not say NOT to use release 0.6.2.  Release 0.6.1 says it is release 0.6.0. So Release 0.6.2 should have been the same as 0.6.1 but with the version number bumped...but I am not sure what is there.

I don't like downloading the master for the reason you give. Was hoping they would do another clean release so we could use that instead.

There is an alternative Yaml module.  It would require a little coding to fit it in but it might be worth it.

**Comment by breznak** [comment] 2019-04-02 14:04
> I don't like downloading the master for the reason you give. Was hoping they would do another clean release so we could use that instead.

https://github.com/jbeder/yaml-cpp/archive/bd7f8c60c82614bb0bd1c526db2cbc39dac02fec.zip 
you can replace master with any commit from the repo, getting exactly that commit. 
Above downloads master as of today.

**Comment by abuMAK** [comment] 2019-04-02 14:06
@dkeeney thanks!! , after I download the yaml-master it's finally succeed to build the package :-). 
After building is done, How I can use it in python ? 
The python building and binding are automatically created via the tartupMSVC.bat , or I need to do something in addition ? , how to add this package into my env (Pycharm)
Thanks,
MAK

**Comment by dkeeney** [comment] 2019-04-02 15:16
>  or I need to do something in addition ?

startupMSVC.bat sets up MSVC to run as your IDE.  If you were doing C++ or using MSVC's Python you have what you need.

To just run Python apps, you need to build and install the Python extension library into your Python installation.  To do that you need to do the following in a command prompt:
```
   cd to_top_of_repository
   python3 setup.py install --user --force
```
Then you can run python apps that contain references to the nupic library.  I suggest looking at the python code in the nupic.py repository.

**Comment by breznak** [comment] 2019-04-04 09:28
I think we can successfully close this! :+1: 
Thanks @dkeeney for all the support!

**Closed by breznak** 2019-04-04 09:28 UTC
