### ISSUE TITLE
invalid free error in log, Release mode

### ISSUE THREAD

**Issue by ctrl-z-9000-times** [htm-community/nupic.cpp#250] opened 2019-02-05 17:27 UTC
Only happens in Release mode, linux.

I have an idea about why this happens, and an idea for how to fix it.  I will probably submit a PR tonight or tomorrow.

**Comment by ctrl-z-9000-times** [comment] 2019-02-06 04:01
I can't seem to reproduce this issue.

**Comment by dkeeney** [comment] 2019-02-06 14:29
It can be caused by a pointer that is capitulated into more than one shared_ptr at the same time. I have tried to be very careful that does not happen but I may have missed something.

I ran the unit_tests, release mode on my Ubuntu 18 and did not see the problem either.

**Comment by breznak** [comment] 2019-02-27 12:30
Closing, please reopen if happens again or if needed.

**Closed by breznak** 2019-02-27 12:30 UTC
Labels: bug, needsinfo
